### ISSUE TITLE
minitests fail on Chef 12.4

### ISSUE THREAD

**Issue by mfischer-zd** [gmiranda23/ntp#122] opened 2015-08-28 20:25 UTC
Under Chef 12.4.1 the default minitest fails with:

```
       ntp::default#test_0001_starts the NTP daemon:
       Chef::Exceptions::Override: You must override load_current_resource in #<Chef::Provider::Service:0x00000007584c90>
           /opt/chef/embedded/apps/chef/lib/chef/provider.rb:95:in `load_current_resource'
```

I'm not sure who's to blame here: Chef, minitest-chef-handler, or this cookbook.

**Comment by dafyddcrosby** [comment] 2015-09-03 19:04
getting it with non-ntp cookbook, so either Chef or minitest-chef-handler

**Comment by tas50** [comment] 2015-12-16 22:29
I'm unable to reproduce this on Chef 12.5.1 with the newest handler cookbook so this looks like an issue in core chef or in the handler cookbook.  I'm going to close this out unless you can repro it on 12.5.1 or 12.6 when that ships.

**Closed by tas50** 2015-12-16 22:29 UTC
