### ISSUE TITLE
Ubuntu 15.04: no systemd init script for ntp

### ISSUE THREAD

**Issue by ckonstanski** [gmiranda23/ntp#108] opened 2015-05-14 18:54 UTC
Ubuntu 15.04's ntp package does not include an /etc/init/ntp.conf. Therefore the systemctl commands fail.

Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl enable ntp ----
    STDOUT: 
    STDERR: Synchronizing state for ntp.service with sysvinit using update-rc.d...
    Executing /usr/sbin/update-rc.d ntp defaults
    Executing /usr/sbin/update-rc.d ntp enable
    Failed to execute operation: No such file or directory
    ---- End output of /bin/systemctl enable ntp ----
    Ran /bin/systemctl enable ntp returned 1

**Comment by shortdudey123** [comment] 2015-05-14 19:49
Dupe of https://github.com/gmiranda23/ntp/issues/105

**Comment by gmiranda23** [comment] 2015-05-14 21:20
@shortdudey123 is correct.  ubuntu 15.04 also doesn't fall into the official chef-client support policy [1].   meaning there's also no ubuntu 15.04 bento box [2] available for support via test-kitchen.

i'm happy to pull in support for this if someone would like to create that basebox, make it publicly available, and submit a PR.  or you can likely use the wrapper cookbook workaround mentioned in #105 

[1] https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md
[2] https://github.com/chef/bento

**Comment by jeremiahsnapp** [comment] 2015-11-06 13:21
I know 15.04 still doesn't fall into tier 1 support but I figured I'd point out that the Ubuntu 15.04 bento box is available now in case the work to fix this issue is relatively small.

https://github.com/chef/bento#pre-built-boxes

**Comment by tas50** [comment] 2015-12-16 22:30
I'm going to release what we have in master right now and then I'll see if I can fix this since the same issue will be in 16.04 when that ships I imagine.

**Comment by tas50** [comment] 2016-02-04 19:15
I've tested this against the master release and it works fine with Chef 12.  I'm going to close this out now.

**Closed by tas50** 2016-02-04 19:15 UTC
Labels: enhancement
